spring.application.name=JmAuditLogging
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/job_matrix_local
spring.datasource.username=job_matrix
spring.datasource.password=job_matrix
spring.datasource.driver-class-name =org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10

spring.profiles.active=local

# Kafka Bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group ID
spring.kafka.consumer.group-id=job-audit-topic

# Key/value deserialization
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Enable auto-commit to false for manual offset management
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest

# Configure the container factory to use manual acknowledgment
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

# Ensure only one consumer instance processes each message
spring.kafka.consumer.client-id=audit-log-consumer
spring.kafka.listener.concurrency=1
spring.kafka.consumer.max-poll-records=1

# Kafka Topics
audit.logging.topic=audit-logging-topic

